# Generated by Django 5.2.10 on 2026-02-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="favorite_color",
            field=models.TextField(default="blue", max_length=32),
            preserve_default=False,
        ),
    ]
