# Generated by Django 5.2.11 on 2026-03-03 09:22

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Image must be 200px by 200px.",
                upload_to="avatars/",
                validators=[users.models.validate_avatar],
            ),
        ),
    ]
