# Generated by Django 5.2.11 on 2026-03-03 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jokes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jokevote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jokevotes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="joke",
            name="tags",
            field=models.ManyToManyField(to="jokes.tag"),
        ),
        migrations.AddConstraint(
            model_name="jokevote",
            constraint=models.UniqueConstraint(
                fields=("user", "joke"), name="one_vote_per_user_per_joke"
            ),
        ),
    ]
