# Generated by Django 5.2.11 on 2026-03-03 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jokes", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="joke",
            options={},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["tag"]},
        ),
        migrations.AddField(
            model_name="joke",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="category",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="joke",
            name="answer",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="joke",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="jokes.category"
            ),
        ),
        migrations.AlterField(
            model_name="joke",
            name="question",
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="joke",
            name="tags",
            field=models.ManyToManyField(blank=True, to="jokes.tag"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name="joke",
            table=None,
        ),
    ]
