# Generated by Django 5.2.10 on 2026-02-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jokes", "0002_alter_joke_answer_alter_joke_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="joke",
            name="slug",
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
