# Generated by Django 5.2.10 on 2026-02-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jokes", "0003_joke_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joke",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
