# Generated by Django 5.2.10 on 2026-02-05 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jokes", "0004_alter_joke_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="joke",
            options={"ordering": ["-updated"]},
        ),
        migrations.RemoveField(
            model_name="joke",
            name="rating",
        ),
    ]
