# Generated by Django 5.2.10 on 2026-02-06 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jokes", "0006_category_joke_categories"),
    ]

    operations = [
        migrations.RenameField(
            model_name="joke",
            old_name="categories",
            new_name="category",
        ),
    ]
